### ISSUE TITLE
Why the Velocity of the Points is 0.0?

### ISSUE THREAD

**Issue by Noricks** [nesl/RadHAR#3]
Hello,
     Your work and the dataset are impressive. 
     I am going to create the Range-Doppler Map from the provided point could frames (I do not have concrete knowledge about FMCW. It is a native idea). 
     However, I found that the velocity of the data points (I have checked some of the files) is always 0.0, which is wired based on my native understanding. Could you please tell me something about it?
     Looking forward to your reply. Thank you!

**Comment by thecyclone** [comment]
Hi Noricks,

I expect this to be due to 2 reasons:

1) Most of the points in the frame are not from the moving target but from the background (walls and ceilings).

2) The. package that we used to collect this data does not give a good estimation for velocity. If you want to build doppler-maps, I would suggest you look at other packages such as the one given here (we use this package now ): https://github.com/ibcn-cloudlet/ti_mmwave_rospkg

**Comment by thecyclone** [comment]
Hi Noricks,

I expect this to be due to 2 reasons:

1) Most of the points in the frame are not from the moving target but from the background (walls and ceilings).

2) The package rounds down small values of velocity to 0.0. In our dataset, we were not moving very fast, so I expect the smaller values were rounded down to 0.0. In you want to make accurate range-doppler maps, you can either edit the package as shown in this paper (https://ieeexplore.ieee.org/abstract/document/8585077) or use a different package to collect your own data: https://github.com/ibcn-cloudlet/ti_mmwave_rospkg (This is what we use now for our experiments).

**Comment by Noricks** [comment]
Thank you for your fast and patient reply!
